from . import hr_allowance
from . import hr_contract
from . import hr_department
from . import hr_employee
from . import hr_employee_salary_change
from . import hr_headquarter
from . import hr_nominal_position
from . import hr_payroll_structure
from . import hr_payslip
from . import hr_salary_tab
from . import res_config
