image: alpine:latest

variables:
  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  KUBE_INGRESS_BASE_DOMAIN: gke.binauraldev.com

  DOCKER_DRIVER: overlay2
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

stages:  
  - test
  - release
  - production  
  - cleanup

  
#include:
#  - project: 'binaural/ecosistema/DevOps/CI-CD/ymls'
#    file: '/code-quality.gitlab-ci.yml'
#  - project: binaural/ecosistema/DevOps/ci-cd/ymls
#    file: /semantic-versioning/release.gitlab-ci.yml
#  - project: binaural/ecosistema/DevOps/ci-cd/ymls
#    file: /sast.gitlab-ci.yml
