version: '3.5'
services:
  web-cumming:
    #image: odoo:14
    build:
      context: .
    container_name: cumming_container
    depends_on:
      - db-cumming
    ports:
      - "15100:8069"
    volumes:
      - odoo-web-cumming:/var/lib/odoo
      - ./config:/etc/odoo
      - ./enterprise:/mnt/extra-addons
      - ./modules:/mnt/custom-addons
      - ./custom:/mnt/another-addons
    environment:
      - PYTHONUNBUFFERED=0
  db-cumming:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-cumming:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-cumming:
  odoo-db-cumming: